var searchData=
[
  ['test_20files_0',['Test Files',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md34',1,'']]],
  ['test_20suite_20description_1',['BSW Test Suite Description',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html',1,'']]],
  ['test_5fboot_20py_20—_20nominal_20boot_20path_20command_201_2',['&lt;span class=&quot;tt&quot;&gt;test_boot.py&lt;/span&gt; — Nominal Boot Path (command &apos;1&apos;)',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md35',1,'']]],
  ['test_5flifecycle_20py_20—_20multi_20step_20lifecycle_20scenarios_3',['&lt;span class=&quot;tt&quot;&gt;test_lifecycle.py&lt;/span&gt; — Multi-Step Lifecycle Scenarios',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md67',1,'']]],
  ['test_5fprotocol_20py_20—_20ecss_20packet_20protocol_20robustness_4',['&lt;span class=&quot;tt&quot;&gt;test_protocol.py&lt;/span&gt; — ECSS Packet Protocol Robustness',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md74',1,'']]],
  ['test_5fswap_20py_20—_20image_20swap_20path_20command_203_5',['&lt;span class=&quot;tt&quot;&gt;test_swap.py&lt;/span&gt; — Image Swap Path (command &apos;3&apos;)',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md56',1,'']]],
  ['test_5fupdate_20py_20—_20firmware_20update_20path_20command_202_6',['&lt;span class=&quot;tt&quot;&gt;test_update.py&lt;/span&gt; — Firmware Update Path (command &apos;2&apos;)',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md46',1,'']]],
  ['testautomaticrollbackbothfail_7',['TestAutomaticRollbackBothFail',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md71',1,'']]],
  ['testautomaticrollbacksecondsucceeds_8',['TestAutomaticRollbackSecondSucceeds',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md72',1,'']]],
  ['testbootbadmagic_9',['TestBootBadMagic',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md42',1,'']]],
  ['testbootbothsectorsunprotected_10',['TestBootBothSectorsUnprotected',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md41',1,'']]],
  ['testbootcorruptcrc_11',['TestBootCorruptCRC',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md38',1,'']]],
  ['testbootinvalidsignature_12',['TestBootInvalidSignature',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md43',1,'']]],
  ['testbootnoimage_13',['TestBootNoImage',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md37',1,'']]],
  ['testbootnominalautofix_14',['TestBootNominalAutoFix',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md44',1,'']]],
  ['testbootunprotectedbswstatesector_15',['TestBootUnprotectedBSWStateSector',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md40',1,'']]],
  ['testbootunprotectedmainsector_16',['TestBootUnprotectedMainSector',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md39',1,'']]],
  ['testbootvalidimage_17',['TestBootValidImage',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md36',1,'']]],
  ['testcommandwithemptydata_18',['TestCommandWithEmptyData',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md76',1,'']]],
  ['testconsecutiveswaps_19',['TestConsecutiveSwaps',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md69',1,'']]],
  ['testfullupdatecycle_20',['TestFullUpdateCycle',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md68',1,'']]],
  ['testrollbackcounterboundary_21',['TestRollbackCounterBoundary',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md54',1,'']]],
  ['testrollbackprevention_22',['TestRollbackPrevention',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md53',1,'']]],
  ['testrollbackwithwindow_23',['TestRollbackWithWindow',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md70',1,'']]],
  ['tests_24',['Key Invariants Verified Across All Tests',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md81',1,'']]],
  ['testswapbadupdateslot_25',['TestSwapBadUpdateSlot',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md61',1,'']]],
  ['testswapbothsectorsstillprotected_26',['TestSwapBothSectorsStillProtected',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md60',1,'']]],
  ['testswapbswstatesectorstillprotected_27',['TestSwapBSWStateSectorStillProtected',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md59',1,'']]],
  ['testswaphappypath_28',['TestSwapHappyPath',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md57',1,'']]],
  ['testswapmainsectorstillprotected_29',['TestSwapMainSectorStillProtected',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md58',1,'']]],
  ['testswapprimarysloterased_30',['TestSwapPrimarySlotErased',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md65',1,'']]],
  ['testswaprollbackcounteredges_31',['TestSwapRollbackCounterEdges',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md63',1,'']]],
  ['testswaprollbackenforcement_32',['TestSwapRollbackEnforcement',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md64',1,'']]],
  ['testswapversionrejectionrecovery_33',['TestSwapVersionRejectionRecovery',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md62',1,'']]],
  ['testunknowncommand_34',['TestUnknownCommand',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md75',1,'']]],
  ['testupdatehappypath_35',['TestUpdateHappyPath',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md47',1,'']]],
  ['testupdatesectorprotectedduringupdate_36',['TestUpdateSectorProtectedDuringUpdate',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md51',1,'']]],
  ['testupdatestateaftersuccess_37',['TestUpdateStateAfterSuccess',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md52',1,'']]],
  ['testupdateunprotectedbswstatesector_38',['TestUpdateUnprotectedBSWStateSector',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md50',1,'']]],
  ['testupdateunprotectedmainsector_39',['TestUpdateUnprotectedMainSector',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md49',1,'']]],
  ['testupdateversiontoolow_40',['TestUpdateVersionTooLow',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md48',1,'']]],
  ['testuploadchunkerrors_41',['TestUploadChunkErrors',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md78',1,'']]],
  ['testuploadendbeforealldata_42',['TestUploadEndBeforeAllData',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md79',1,'']]],
  ['testuploadstarterrors_43',['TestUploadStartErrors',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md77',1,'']]],
  ['type_200x01_44',['NOMINAL boot (type = 0x01)',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md30',1,'']]],
  ['type_200x02_45',['UPDATE (type = 0x02)',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md31',1,'']]],
  ['type_200x03_46',['SWAP (type = 0x03)',['../md__t_e_s_t___s_u_i_t_e___d_e_s_c_r_i_p_t_i_o_n.html#autotoc_md32',1,'']]]
];
